### ISSUE TITLE
Allow `brand` to be configured on a per-component basis

### ISSUE THREAD

**Issue by paulrobertlloyd** [x-govuk/govuk-components#547]
We’re using this library [with `conf.brand` set to `'nhsuk'`](https://github.com/nhsuk/manage-vaccinations-in-schools/blob/4f87bc3a4c05143bdc654f9e3e2451964b6ee3c7/config/initializers/govuk_components.rb#L3), and importing `nhsuk-frontend` to style the generated component markup.

In most cases this works because there’s reasonable closeness between the CSS classes used by `govuk-frontend`, and those used by `nhsuk-frontend`:

```erb
<%= govuk_link_to 'A regular hyperlink', '#' %>
```

```html
<!-- nhsuk-frontend provides styles for `nhsuk-link` -->
<a class="nhsuk-link" href="#">A regular hyperlink</a>
```

However, given the following component, which has no equivalent in `nhsuk-frontend`:

```erb
<%= govuk_panel(
  title_text: "Application complete",
  text: "You will soon receive an email confirmation."
) %>
```

```html
<!-- nhsuk-frontend does not provide styles for `nhsuk-panel` -->
<div class="nhsuk-panel nhsuk-panel--confirmation">
  <h1 class="nhsuk-panel__title">Application complete</h1>
  <div class="nhsuk-panel__body">You will soon receive an email confirmation.</div>
</div>
```

Because `nhsuk-frontend` doesn’t support these classes, we need to do the following in our SCSS (approximated):

```scss
// Configure and import GOV.UK Frontend
$govuk-font-family: "Frutiger W01", Arial, sans-serif;
$govuk-brand-colour: #005eb8;

// Import panel component styles
@import "govuk-frontend/dist/govuk/components/panel/index";

// Apply the panel component styles to the nhsuk- prefixed component
.nhsuk-panel {
  @extend .govuk-panel;

  &--confirmation {
    @extend .govuk-panel--confirmation;
  }

  &__title {
    @extend .govuk-panel__title;
  }
}
```

## Proposal

By allowing `brand` to be set at the component level, components can opt in or out of a configured brand, or use multiple brand prefixes. The above would therefore become:

```erb
<%= govuk_panel(
  title_text: "Application complete",
  text: "You will soon receive an email confirmation.",
  brand: "govuk"
) %>
```

```html
<div class="govuk-panel govuk-panel--confirmation">
  <h1 class="govuk-panel__title">Application complete</h1>
  <div class="govuk-panel__body">You will soon receive an email confirmation.</div>
</div>
```

```scss
// Configure and import GOV.UK Frontend
$govuk-font-family: "Frutiger W01", Arial, sans-serif;
$govuk-brand-colour: #005eb8;

@import "govuk-frontend/dist/govuk/components/panel/index";
```
